# Generated by Django 3.1.6 on 2021-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_entry_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
