# Generated by Django 3.1.6 on 2021-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20210519_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_text_short',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
