# Generated by Django 3.1.6 on 2021-04-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_entry_entry_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_author',
        ),
    ]
